<Project>
	<PropertyGroup>
	<FaviconExtractorMSTestAdapterVersion Condition="'$(FaviconExtractorMSTestAdapterVersion)' == ''">2.2.10</FaviconExtractorMSTestAdapterVersion>
	<FaviconExtractorMSTestAdapterPath Condition="'$(FaviconExtractorMSTestAdapterPath)' == ''">$(MSBuildThisFileDirectory)packages\MSTest.TestAdapter.$(FaviconExtractorMSTestAdapterVersion)\build\_common</FaviconExtractorMSTestAdapterPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release' and '$(PackagePluginOnBuild)' == ''">
	<PackagePluginOnBuild>true</PackagePluginOnBuild>
  </PropertyGroup>
</Project>
