<Project>
  <Target Name="PackagePluginArtifacts"
		  AfterTargets="Build"
		  Condition="'$(PackagePluginOnBuild)' == 'true' and '$(Configuration)' == 'Release' and '$(MSBuildProjectName)' == 'KeepassFaviconExtractor'">
	<Exec Command="powershell -NoProfile -ExecutionPolicy Bypass -File &quot;$(MSBuildProjectDirectory)\scripts\build-release.ps1&quot; -Configuration $(Configuration) -SkipBuild -KeePassExePath &quot;$(KeePassDir)\KeePass.exe&quot;" />
  </Target>
</Project>
